name: 자동 검색 실행

on:
  schedule:
    # 매 1시간마다 체크하여 설정된 interval_hours에 따라 실행
    - cron: '0 * * * *'
    # 디버그/안정성 확보용 임시 주기(15분마다). 필요시 제거 가능
    - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      schedule_id:
        description: '실행할 스케줄 ID (선택사항)'
        required: false
        type: string
      api_key_profile_id:
        description: '사용할 API 키 프로필 ID (선택사항)'
        required: false
        type: string
      force_run:
        description: '간격 체크 무시하고 강제로 실행 (true/false)'
        required: false
        type: boolean
        default: false

jobs:
  auto-search:
    runs-on: ubuntu-latest
    
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v4

      - name: 러너 도구 설치 (jq, bc)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq bc

      - name: Node.js 설정
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: 의존성 설치
        run: npm ci

      - name: 활성화된 설정 조회 및 실행 시간 확인
        id: get-configs
        run: |
          echo "트리거: $GITHUB_EVENT_NAME, 현재 UTC 시간: $(date -u)"
          # 모든 활성화된 설정 조회 (interval_hours 포함)
          CONFIGS_JSON=$(curl -s -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "apikey: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            "${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}/rest/v1/auto_search_configs?is_active=eq.true&select=id,interval_hours,last_run_at" \
            | jq -r '.')
          
          echo "설정 조회 결과: $CONFIGS_JSON"
          
          # 실행할 설정들 필터링
          EXECUTE_CONFIGS=""
          
          # 현재 시간 (UTC)
          CURRENT_TIME=$(date -u +%s)
          echo "현재 시간 (UTC): $(date -u)"

          # 강제 실행 플래그
          FORCE_RUN_INPUT="${{ github.event.inputs.force_run }}"
          FORCE_RUN=false
          if [ "$FORCE_RUN_INPUT" = "true" ] || [ "$FORCE_RUN_INPUT" = "True" ]; then
            FORCE_RUN=true
          fi
          echo "강제 실행 여부: $FORCE_RUN"
          
          # 각 설정별로 실행 시간 확인
          while IFS= read -r config; do
            CONFIG_DATA=$(echo "$config" | base64 -d)
            CONFIG_ID=$(echo "$CONFIG_DATA" | jq -r '.id')
            INTERVAL_HOURS=$(echo "$CONFIG_DATA" | jq -r '.interval_hours')
            LAST_RUN_AT=$(echo "$CONFIG_DATA" | jq -r '.last_run_at')
            
            echo "설정 $CONFIG_ID: interval_hours=$INTERVAL_HOURS, last_run_at=$LAST_RUN_AT"
            
            # 강제 실행이면 무조건 실행
            if [ "$FORCE_RUN" = true ]; then
              echo "설정 $CONFIG_ID: 강제 실행 옵션으로 실행"
              EXECUTE_CONFIGS="$EXECUTE_CONFIGS $CONFIG_ID"
            # 마지막 실행 시간이 없거나 설정된 간격이 지났으면 실행
            elif [ "$LAST_RUN_AT" = "null" ] || [ -z "$LAST_RUN_AT" ]; then
              echo "설정 $CONFIG_ID: 첫 실행"
              EXECUTE_CONFIGS="$EXECUTE_CONFIGS $CONFIG_ID"
            else
              # 마지막 실행 시간을 초로 변환
              LAST_RUN_TIME=$(date -d "$LAST_RUN_AT" -u +%s 2>/dev/null || echo "0")
              # interval_hours를 초로 변환 (소수점 처리 후 정수부만 사용)
              INTERVAL_SECONDS=$(echo "$INTERVAL_HOURS * 3600" | bc -l | awk -F. '{print $1}')
              TIME_DIFF=$((CURRENT_TIME - LAST_RUN_TIME))
              
              echo "설정 $CONFIG_ID: 마지막 실행 후 $TIME_DIFF초 경과, 필요 간격: $INTERVAL_SECONDS초"
              
              if [ "$TIME_DIFF" -ge "$INTERVAL_SECONDS" ]; then
                echo "설정 $CONFIG_ID: 실행 시간 도달"
                EXECUTE_CONFIGS="$EXECUTE_CONFIGS $CONFIG_ID"
              else
                echo "설정 $CONFIG_ID: 아직 실행 시간이 아님"
              fi
            fi
          done <<< "$(echo "$CONFIGS_JSON" | jq -r '.[] | @base64')"
          
          # 실행할 설정이 있으면 실행
          if [ -n "$EXECUTE_CONFIGS" ]; then
            echo "configs=$EXECUTE_CONFIGS" >> $GITHUB_OUTPUT
            echo "실행할 설정: $EXECUTE_CONFIGS"
          else
            echo "configs=" >> $GITHUB_OUTPUT
            echo "실행할 설정이 없습니다."
          fi

      - name: 자동 검색 실행
        if: steps.get-configs.outputs.configs != ''
        run: |
          # 환경변수 설정
          export SUPABASE_URL="${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}"
          export SUPABASE_SERVICE_KEY="${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"
          
          # 실행할 설정 ID들을 배열로 변환
          CONFIGS="${{ steps.get-configs.outputs.configs }}"
          echo "실행할 설정들: $CONFIGS"
          
          # 각 설정별로 자동 검색 실행
          for config_id in $CONFIGS; do
            if [ -n "$config_id" ]; then
              echo "설정 $config_id 실행 중..."
              node scripts/auto-search.js $config_id
            fi
          done

      - name: 실행 결과 요약
        if: always()
        run: |
          echo "자동 검색 실행이 완료되었습니다."
          echo "실행된 설정: ${{ steps.get-configs.outputs.configs }}"